apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loginsight.fullname" . }}-kafka-config
  labels:
    {{- include "loginsight.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_TOPIC:             {{ .Values.kafka.topic | quote }}
  KAFKA_GROUP_ID:          {{ .Values.kafka.groupId | quote }}
  ELASTICSEARCH_URL:       {{ .Values.elasticsearch.url | quote }}
  INFLUXDB_URL:            {{ .Values.influxdb.url | quote }}
  INFLUXDB_ORG:            {{ .Values.influxdb.org | quote }}
  INFLUXDB_BUCKET:         {{ .Values.influxdb.bucket | quote }}
  S3_BUCKET:               {{ .Values.s3.bucket | quote }}
  AWS_REGION:              {{ .Values.s3.region | quote }}
  OTEL_PROMETHEUS_PORT:    {{ .Values.telemetry.prometheusPort | quote }}
  SERVICE_NAME:            "loginsight-ingestion"
  ALERTS_TOPIC:            {{ .Values.kafka.alertsTopic | quote }}
  METRICS_FLUSH_INTERVAL_SECONDS: {{ .Values.metrics.flushIntervalSeconds | quote }}
